const data = [
  {
    id: 1,
    location: 'Kinoo, Waiyaki Way',
    distance: '2.5 km Walk from Sarit Centre',
    price: 15000,
    bedRooms: 2,
    bathRooms: 1,
    image: 'https://unsplash.com/photos/a-bedroom-with-a-bed-and-a-mirrored-wall-nO87kT1vjSE',
  },
  {
    id: 2,
    location: 'Kilimani, Nairobi',
    distance: '1.2 km from Yaya Centre',
    price: 60000,
    bedRooms: 3,
    bathRooms: 2,
    image: 'https://unsplash.com/photos/a-living-room-filled-with-furniture-and-a-flat-screen-tv-nmKPgfIUYtM',
  },
  {
    id: 3,
    location: 'Westlands, Nairobi',
    distance: '500 m from Sarit Centre',
    price: 145000,
    bedRooms: 4,
    bathRooms: 3,
    image: 'https://unsplash.com/photos/3d-render-of-modern-living-room-X5ZtJe5dnzs',
  },
    {
        id: 4,
        location: 'Karen, Nairobi',
        distance: '3 km from Galleria Mall',
        price: 30000,
        bedRooms: 0,
        bathRooms: 1,
        image: 'https://unsplash.com/photos/3d-render-modern-hotel-room-with-two-bed-fjaFyWWnhzk',
    },
    {
        id: 5,
        location: 'Runda, Nairobi',
        distance: '1.5 km from Village Market',
        price: 350000,
        bedRooms: 6,
        bathRooms: 5,
        image: 'https://unsplash.com/photos/3d-render-of-modern-and-luxury-home-NAVHX4j6PJg',
    },
    {
        id: 6,
        location: 'Langata, Nairobi',
        distance: '2 km from Gikambura',
        price: 18000,
        bedRooms: 1,
        bathRooms: 1,
        image: 'https://unsplash.com/photos/a-living-room-filled-with-furniture-and-a-flat-screen-tv-VhauWHf-m4Q',
    },
    {
        id: 7,
        location: 'Kasarani, Nairobi',
        distance: '1 km from Safari Park Hotel',
        price: 22000,
        bedRooms: 1,
        bathRooms: 1,
        image: 'https://unsplash.com/photos/tidy-room-filled-with-furnitures-gREquCUXQLI',
    },
    {
        id: 8,
        location: 'Mombasa Road, Nairobi',
        distance: '2.5 km from Panari Sky Centre',
        price: 38000,
        bedRooms: 2,
        bathRooms: 2,
        image: 'https://unsplash.com/photos/a-living-room-filled-with-furniture-and-lots-of-windows-4Q30ii7xtls',
    },
    {
        id: 9,
        location: 'Kikuyu, Nairobi',
        distance: '3 km from T-Mall',
        price: 16000,
        bedRooms: 2,
        bathRooms: 1,
        image: 'https://images.unsplash.com/photo-1607523308850-2c8b1f3d4c5e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60',
    },
    {
        id: 10,
        location: 'Uthiru, Nairobi',
        distance: '4 km from Sarova Panafric',
        price: 14000,
        bedRooms: 1,
        bathRooms: 1,
        image: 'https://unsplash.com/photos/a-living-room-filled-with-furniture-and-a-table-txs_wyWEdus',
    },
    {
        id: 11,
        location: 'Kangemi, Nairobi',
        distance: '2 km from Sarit Centre',
        price: 17000,
        bedRooms: 2,
        bathRooms: 2,
        image: 'https://unsplash.com/photos/an-interior-of-modern-room-in-luxury-hotel-s4yfYIz964U',
    },
    {
        id: 12,
        location: 'Kibera, Nairobi',
        distance: '1 km from Kenyatta National Hospital',
        price: 12000,
        bedRooms: 2,
        bathRooms: 1,
        image: 'https://unsplash.com/photos/white-corner-sofa-inside-living-room-AIHst2T1Iqk',
    },
    {
        id: 13,
        location: 'Kawangware, Nairobi',
        distance: '2 km from Lavington Mall',
        price: 13000,
        bedRooms: 2,
        bathRooms: 1,
        image: 'https://unsplash.com/photos/modern-chalet-interior-3d-rendering-design-concept-_Jz3HfmNSV4',
    },
    {
        id: 14,
        location: 'Lavington, Nairobi',
        distance: '1.5 km from Prestige Cinema',
        price: 240000,
        bedRooms: 3,
        bathRooms: 3,
        image: 'https://unsplash.com/photos/modern-chalet-interior-3d-rendering-design-concept-bnwA4bad87A',
    },
    {
        id: 15,
        location: 'Parklands, Nairobi',
        distance: '2 km from Sarit Centre',
        price: 22000,
        bedRooms: 0,
        bathRooms: 1,
        image: 'https://unsplash.com/photos/a-living-room-with-a-couch-and-a-table-bkEsbNTrIF8',
    },
];